language: java
jdk:
  - oraclejdk11
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)